"""Synthetic profile generation for Module 1.

Generates 15 solar building profiles and 5 consumer building profiles
from the college reference data using load scaling, temporal shifting,
seasonal variation, occupancy variation, and weekend effects.

Design reference: docs/module_1_profile_generator.md
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

import numpy as np
import pandas as pd

from p2p_energy_trading.constants import (
    INTERNAL_COL_DEMAND,
    INTERNAL_COL_SOLAR,
    INTERNAL_COL_TIMESTAMP,
    NUM_CONSUMER,
    NUM_SOLAR,
)
from p2p_energy_trading.exceptions import ProfileGenerationError

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Building type configuration — from module_1_profile_generator.md
# ---------------------------------------------------------------------------

# Solar buildings: 30%-80% of college load
SOLAR_LOAD_SCALE_MIN: float = 0.30
SOLAR_LOAD_SCALE_MAX: float = 0.80

# Consumer buildings: 10%-30% of college load
CONSUMER_LOAD_SCALE_MIN: float = 0.10
CONSUMER_LOAD_SCALE_MAX: float = 0.30

# Temporal shift: +-3 hours
MAX_SHIFT_HOURS: int = 3

# Weekend multipliers
SATURDAY_MULTIPLIER_MIN: float = 0.60
SATURDAY_MULTIPLIER_MAX: float = 0.80
SUNDAY_MULTIPLIER_MIN: float = 0.40
SUNDAY_MULTIPLIER_MAX: float = 0.60

# Occupancy: random daily variation around 1.0
OCCUPANCY_STD: float = 0.05


@dataclass
class BuildingProfile:
    """A single building's energy profile.

    Attributes:
        building_id: Unique identifier (e.g. 'solar_01', 'consumer_03').
        building_type: One of 'college', 'solar', 'consumer'.
        df: DataFrame with columns timestamp, demand_kw, solar_generation_kw.
        load_scale: Scaling factor applied to college demand.
        solar_scale: Scaling factor applied to college solar (0.0 for consumers).
        shift_hours: Temporal shift applied (in hours).
        seed: Random seed used to generate this profile.
    """

    building_id: str
    building_type: str
    df: pd.DataFrame
    load_scale: float
    solar_scale: float
    shift_hours: int
    seed: int


def generate_college_profile(college_df: pd.DataFrame) -> BuildingProfile:
    """Return the college building profile unchanged.

    The college building uses the real, unmodified dataset as its profile.

    Args:
        college_df: Validated DataFrame with internal column names.

    Returns:
        BuildingProfile for the college with a copy of the raw data.
    """
    df = college_df[[INTERNAL_COL_TIMESTAMP, INTERNAL_COL_DEMAND, INTERNAL_COL_SOLAR]].copy()
    logger.info("College profile: %d samples (real, unmodified)", len(df))
    return BuildingProfile(
        building_id="college",
        building_type="college",
        df=df,
        load_scale=1.0,
        solar_scale=1.0,
        shift_hours=0,
        seed=0,
    )


def generate_solar_profiles(
    college_df: pd.DataFrame,
    count: int = NUM_SOLAR,
    base_seed: int = 42,
) -> list[BuildingProfile]:
    """Generate synthetic profiles for solar buildings.

    Each solar building profile is generated by:
    - Load scaling: 30%-80% of college demand
    - Solar scaling: 30%-80% of college solar (same factor, uncorrelated via seed)
    - Temporal shifting: +-3 hours (circular roll)
    - Seasonal effects: inherited from the college reference signal
    - Weekend effects: Saturday 60%-80%, Sunday 40%-60% multiplier
    - Occupancy variation: per-day random multiplier

    Args:
        college_df: Validated DataFrame with internal column names.
        count: Number of solar buildings to generate.
        base_seed: Base random seed; each building uses base_seed + index.

    Returns:
        List of BuildingProfile objects, one per solar building.

    Raises:
        ProfileGenerationError: If the college DataFrame is malformed.
    """
    _check_input_df(college_df, "college_df")
    profiles: list[BuildingProfile] = []

    for i in range(1, count + 1):
        seed = base_seed + i
        rng = np.random.default_rng(seed)

        load_scale = float(rng.uniform(SOLAR_LOAD_SCALE_MIN, SOLAR_LOAD_SCALE_MAX))
        solar_scale = float(rng.uniform(SOLAR_LOAD_SCALE_MIN, SOLAR_LOAD_SCALE_MAX))
        shift_hours = int(rng.integers(-MAX_SHIFT_HOURS, MAX_SHIFT_HOURS + 1))

        df = _apply_transformations(
            college_df=college_df,
            load_scale=load_scale,
            solar_scale=solar_scale,
            shift_hours=shift_hours,
            rng=rng,
            zero_solar=False,
        )

        building_id = f"solar_{i:02d}"
        logger.debug(
            "Generated %s: load_scale=%.2f, solar_scale=%.2f, shift=%+dh",
            building_id,
            load_scale,
            solar_scale,
            shift_hours,
        )
        profiles.append(
            BuildingProfile(
                building_id=building_id,
                building_type="solar",
                df=df,
                load_scale=load_scale,
                solar_scale=solar_scale,
                shift_hours=shift_hours,
                seed=seed,
            )
        )

    logger.info("Generated %d solar building profiles", len(profiles))
    return profiles


def generate_consumer_profiles(
    college_df: pd.DataFrame,
    count: int = NUM_CONSUMER,
    base_seed: int = 100,
) -> list[BuildingProfile]:
    """Generate synthetic profiles for consumer (load-only) buildings.

    Consumer buildings have no solar generation (solar_generation_kw = 0).
    Each profile is generated by:
    - Load scaling: 10%-30% of college demand
    - Solar generation: zero throughout
    - Temporal shifting: +-3 hours (circular roll)
    - Weekend effects: Saturday 60%-80%, Sunday 40%-60% multiplier
    - Occupancy variation: per-day random multiplier

    Args:
        college_df: Validated DataFrame with internal column names.
        count: Number of consumer buildings to generate.
        base_seed: Base random seed; each building uses base_seed + index.

    Returns:
        List of BuildingProfile objects, one per consumer building.

    Raises:
        ProfileGenerationError: If the college DataFrame is malformed.
    """
    _check_input_df(college_df, "college_df")
    profiles: list[BuildingProfile] = []

    for i in range(1, count + 1):
        seed = base_seed + i
        rng = np.random.default_rng(seed)

        load_scale = float(rng.uniform(CONSUMER_LOAD_SCALE_MIN, CONSUMER_LOAD_SCALE_MAX))
        shift_hours = int(rng.integers(-MAX_SHIFT_HOURS, MAX_SHIFT_HOURS + 1))

        df = _apply_transformations(
            college_df=college_df,
            load_scale=load_scale,
            solar_scale=0.0,
            shift_hours=shift_hours,
            rng=rng,
            zero_solar=True,
        )

        building_id = f"consumer_{i:02d}"
        logger.debug(
            "Generated %s: load_scale=%.2f, shift=%+dh",
            building_id,
            load_scale,
            shift_hours,
        )
        profiles.append(
            BuildingProfile(
                building_id=building_id,
                building_type="consumer",
                df=df,
                load_scale=load_scale,
                solar_scale=0.0,
                shift_hours=shift_hours,
                seed=seed,
            )
        )

    logger.info("Generated %d consumer building profiles", len(profiles))
    return profiles


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _check_input_df(df: pd.DataFrame, name: str) -> None:
    """Validate that the input DataFrame has the required columns."""
    required = [INTERNAL_COL_TIMESTAMP, INTERNAL_COL_DEMAND, INTERNAL_COL_SOLAR]
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ProfileGenerationError(
            f"{name} is missing required columns: {missing}"
        )
    if len(df) == 0:
        raise ProfileGenerationError(f"{name} is empty")


def _apply_transformations(
    college_df: pd.DataFrame,
    load_scale: float,
    solar_scale: float,
    shift_hours: int,
    rng: np.random.Generator,
    zero_solar: bool,
) -> pd.DataFrame:
    """Apply all synthetic generation transformations to the college data.

    Applies load scaling, solar scaling, temporal shifting, weekend effects,
    and occupancy variation. All transformations maintain non-negativity.

    Args:
        college_df: Source DataFrame with internal column names.
        load_scale: Scalar multiplier for demand.
        solar_scale: Scalar multiplier for solar (ignored if zero_solar).
        shift_hours: Number of hours to circularly shift the time series.
        rng: Seeded random number generator.
        zero_solar: If True, solar_generation_kw is set to zero.

    Returns:
        DataFrame with timestamp, demand_kw, solar_generation_kw.
    """
    demand = college_df[INTERNAL_COL_DEMAND].values.copy()
    solar = college_df[INTERNAL_COL_SOLAR].values.copy()
    timestamps = college_df[INTERNAL_COL_TIMESTAMP].values.copy()

    # 1. Temporal shift (circular roll)
    if shift_hours != 0:
        demand = np.roll(demand, shift_hours)
        solar = np.roll(solar, shift_hours)

    # 2. Load and solar scaling
    demand = demand * load_scale
    if zero_solar:
        solar = np.zeros_like(solar)
    else:
        solar = solar * solar_scale

    # 3. Occupancy variation (per-day random multiplier)
    timestamps_pd = pd.to_datetime(timestamps)
    dates = timestamps_pd.date
    unique_dates = sorted(set(dates))
    occupancy = {
        d: float(rng.normal(1.0, OCCUPANCY_STD))
        for d in unique_dates
    }
    # Clip occupancy multipliers to sensible range [0.7, 1.3]
    occupancy = {d: max(0.7, min(1.3, v)) for d, v in occupancy.items()}

    occ_multipliers = np.array([occupancy[d] for d in dates])
    demand = demand * occ_multipliers

    # 4. Weekend effects — one multiplier per unique calendar date (daily, not hourly)
    # Pattern mirrors occupancy variation above: build a date→factor mapping first,
    # then broadcast each day's single factor across all hours of that date.
    day_of_week = timestamps_pd.dayofweek  # Monday=0, Sunday=6
    saturday_dates = sorted({d for d, dow in zip(dates, day_of_week) if dow == 5})
    sunday_dates = sorted({d for d, dow in zip(dates, day_of_week) if dow == 6})

    weekend_factor: dict = {}
    for d in saturday_dates:
        weekend_factor[d] = float(rng.uniform(SATURDAY_MULTIPLIER_MIN, SATURDAY_MULTIPLIER_MAX))
    for d in sunday_dates:
        weekend_factor[d] = float(rng.uniform(SUNDAY_MULTIPLIER_MIN, SUNDAY_MULTIPLIER_MAX))

    weekend_multipliers = np.array(
        [weekend_factor.get(d, 1.0) for d in dates]
    )
    demand = demand * weekend_multipliers

    # 5. Clip to non-negative
    demand = np.clip(demand, 0.0, None)
    solar = np.clip(solar, 0.0, None)

    return pd.DataFrame({
        INTERNAL_COL_TIMESTAMP: pd.to_datetime(timestamps),
        INTERNAL_COL_DEMAND: demand.astype(np.float64),
        INTERNAL_COL_SOLAR: solar.astype(np.float64),
    })
